### ISSUE TITLE
problem error

### ISSUE THREAD

**Issue by anwfeb** [SpenceKonde/ATTinyCore#845]
please check your [url](Error downloading https://drazzy.com/package_drazzy.com_index.json)

**Comment by hmeijdam** [comment]
Please check this [workaround](https://github.com/SpenceKonde/megaTinyCore/issues/1059#issuecomment-1950286469)

**Comment by SpenceKonde** [comment]
fixed now

**Comment by gnif** [comment]
And it's broken again. It's a let's encrypt cert, have you forgot to setup your cronjob to renew the cert?

**Comment by per1234** [comment]
The current occurrence of the problem is being tracked at https://github.com/SpenceKonde/ATTinyCore/issues/885. Check **@SpenceKonde**'s comments on that thread for an update on the situation.
